### ISSUE TITLE
请问分布式怎么部署？谢谢

### ISSUE THREAD

**Issue by kisscelia** [Runner-Go-Team/RunnerGo#10]
如题，请问分布式怎么部署？
非常感谢！

开源版好像没有机器管理模块

**Comment by xiwunongyue** [comment]
源码版本分布式已经可以，docker版本还请耐心等待

**Comment by kisscelia** [comment]
好的，谢谢您。
文档没找到，我准备看看源码。

**Comment by xiwunongyue** [comment]
https://wiki.runnergo.cn/docs/67,这是文档

**Comment by kisscelia** [comment]
@xiwunongyue 好的，谢谢您。
