### ISSUE TITLE
性能测试 资源不足

### ISSUE THREAD

**Issue by yuexl** [Runner-Go-Team/RunnerGo#12]
执行性能测试，提示资源不足，docker-compose部署
![image](https://user-images.githubusercontent.com/26302906/226799600-a3527d79-25da-498d-913d-f1b937223ea8.png)

**Comment by xiwunongyue** [comment]
请将docker-compose.yaml文件中的collector镜像换成image: registry.cn-beijing.aliyuncs.com/runnergo/collector:releases-v1.0.2
