### ISSUE TITLE
这也算开源？ 源代码都没有

### ISSUE THREAD

**Issue by Avey777** [Runner-Go-Team/RunnerGo#24]

**Comment by kuwooo** [comment]
稍微往下翻一下readme，也不至于这样说呀 @Avey777 

## 源码清单

### RunnerGo-management-websocket-open
https://github.com/Runner-Go-Team/RunnerGo-management-websocket-open

### RunnerGo-management-open
https://github.com/Runner-Go-Team/RunnerGo-management-open

### RunnerGo-collector-open 
https://github.com/Runner-Go-Team/RunnerGo-collector-open

### RunnerGo-fe-open
https://github.com/Runner-Go-Team/RunnerGo-management-open

### RunnerGo-engine-open
https://github.com/Runner-Go-Team/RunnerGo-engine-open

### file-server 
https://github.com/Runner-Go-Team/file-server

**Comment by Avey777** [comment]
OK 我看错了 微服务架构的
