### ISSUE TITLE
Runnergo 比 Metersphere 还要耗资源

### ISSUE THREAD

**Issue by Avey777** [Runner-Go-Team/RunnerGo#27]
Runnergo  时go语言开发的，虽然是微服务。 但是在一台4核心16G 内存的机器上 运行不应该那么吃力，CPU风扇会一直高功率运行。

同样的配置我部署了MeterSphere 不会出现这样的情况

都只是单机部署，没有进行压测

**Comment by xiwunongyue** [comment]
俩着不是同一款产品，RunnerGo更定位为企业级测试平台，因为定位的是全栈测试平台，肯定是不建议单机部署的，docker版本也只是为了大家体验我们的产品，如果部署还是建议使用源码部署。两者底层实现是不同的。何况我们建议单机也是8c16g，而不是4c8g

**Comment by Avey777** [comment]
![image](https://github.com/Runner-Go-Team/RunnerGo/assets/35259040/db74a6c7-87b4-4c00-9d20-f56f88d6edcc)


单机6核16G，V1.1.4  执行性能测试计划就会报错，这块是做了强制的 8c 16G  的硬件检测吗？

**Comment by Avey777** [comment]
很有意思的是 V1.1.2 版本不会有这个问题，V1.1.3和V1.1.4 就会有这个问题

**Comment by xiwunongyue** [comment]
后续准备把kafka去掉，然后collector服务进行变更后，就不会存在这种问题了。

**Comment by Avey777** [comment]
> 后续准备把kafka去掉，然后collector服务进行变更后，就不会存在这种问题了。

使用KubeMQ 进行替换吗？
